from market_logic import User

class InvalidToken(Exception): ...
class IncorrectPassword(Exception): ...
class AccountAlreadyExists(Exception): ...

class Account:
    username: str
    password: str

    def __init__(self, username: str, password: str) -> None: ...

class Authenticator:
    @staticmethod
    def authenticate_user(account: Account) -> str: ...
    @staticmethod
    def find_user_by_token(token: str) -> User: ...
    @staticmethod
    def logout(token: str) -> None: ...
    @staticmethod
    def register(account: Account, display_name: str) -> None: ...
