from market_logic import User

class InvalidToken(Exception): ...
class IncorrectPassword(Exception): ...

class Account:
    username: str
    password: str

    def __init__(self, username: str, password: str) -> None: ...

def authenticate_user(account: Account) -> str: ...
def find_user_by_token(token: str) -> User: ...
def logout(token: str) -> None: ...
def register(account: Account, display_name: str) -> None: ...
